module.exports = {
  'names': [
    'daisy',
    'molly',
    'lola',
    'madison',
    'heidi',
    'sally',
    'shadow',
    'cocoa',
    'pebbles',
    'misty',
    'nikki',
    'lexie',
    'grace',
    'sierra',
  ],
  'animals': [
    'antelope',
    'ape',
    'armadillo',
    'boar',
    'buffalo',
    'butterfly',
    'chicken',
    'chimpanzee',
    'chinchilla',
    'salamander',
    'salmon',
    'weasel',
    'whale',
    'wolf',
    'wolverine',
  ],
  'places': [
    'india',
    'england',
    'australia',
    'egypt',
    'afghanistan',
    'germany',
    'israel',
    'russia',
    'france',
    'bolivia',
    'cuba',
    'canada',
    'tunisia',
    'indonesia',
    'japan',
    'visakhapatnam',
    'moscow',
  ],
  'nicknames': [
    'romeo',
    'casanova',
    'bubba',
    'maverick',
  	'goose',
  	'chief',
  	'dug',
  	'brah',
  	'bro',
  	'homes',
    'cosmo',
  	'prince',
  	'tarzan',
  	'dex',
  	'hawk',
    'captain',
	  'champ',
  ],
  'colors': [
    'almond',
    'apricot',
    'aquamarine',
    'cornflower',
  	'electric lime',
  	'forest green',
  	'goldenrod',
  	'green',
  	'magneta',
    'purple',
  	'navy blue',
  	'yellow',
  	'black',
    'orange',
	  'red',
  ],
  'things': [
    'sweatshirt',
    'slippers',
    'stockings',
    'pajamas',
  	'umbrella',
  	'scissors',
  	'toothbrush',
  	'magazine',
  	'deodorant',
  	'headphones',
    'hanger',
  	'sneakers',
  	'refrigerator',
  	'mementos',
  	'cushions',
    'dishwasher',
	  'xbox',
  ],
  'sports': [
    'martial arts',
    'basketball',
    'football',
    'baseball',
  	'soccer',
  	'hockey',
  	'gymnastics',
  	'swimming',
  	'tennis',
  	'wrestling',
    'cricket',
  	'badminton',
  	'skateboarding',
  	'nascar',
  	'lacrosse',
    'volleyball',
	  'boxing',
  ],
  'famous personalities': [
    'Marilyn Monroe',
    'Abraham Lincoln',
    'Mother Teresa',
    'Nelson Mandela',
  	'Muhammad Ali',
  	'Mahatma Gandhi',
  	'Leo Tolstoy',
  	'Pablo Picasso',
  	'Walt Disney',
  	'Pele',
    'Angelina Jolie',
  	'Lionel Messi',
  	'Shakira',
  	'Steve Jobs',
  	'Zuckerberg',
    'Vladimir Putin',
	  'Barack Obama',
  ],
  'basketball players': [
    'Tim Duncan',
    'Shaquille ONeal',
    'Larry Bird',
    'Bill Russell',
  	'Oscar Robertson',
  	'Magic Johnson',
  	'Michael Jordan',
  	'LeBron James',
  ],
  'companies': [
    'Apple',
    'Microsoft',
    'Facebook',
    'Google',
  	'Amazon',
  	'Boeing',
  	'Ennovar',
  	'Walmart',
    'Mercedes',
  	'Ford',
    'Pepsi',
  	'ebay',
  ]
};
